"""Protocol-style interfaces for pluggable locator components."""

from __future__ import annotations

from typing import Any, Optional, Protocol, Tuple

import numpy as np

Roi = Tuple[int, int, int, int]


class LocatorProtocol(Protocol):
    """Interface for stateful frame locator implementations."""

    def locate(self, frame: np.ndarray) -> Any: ...
    def get_current_roi(self) -> Optional[Roi]: ...
    def update_roi_from_bbox(self, bbox: Roi) -> None: ...
    def reset_roi(self) -> None: ...


class GeometryTrackerProtocol(Protocol):
    """Interface for geometry reuse / reacquire state machines."""

    @property
    def current_geometry(self) -> Any: ...

    @property
    def current_generation(self) -> int: ...

    def get_current_roi(self) -> Optional[Roi]: ...
    def should_reacquire(self) -> bool: ...
    def force_reacquire(self) -> None: ...
    def locate_frame(self, frame: np.ndarray) -> Any: ...
    def propose_update(self, **kwargs: Any) -> bool: ...
    def record_success(self, **kwargs: Any) -> None: ...
    def record_failure(self, **kwargs: Any) -> None: ...
    def snapshot(self) -> Any: ...
